####################
# CTscanner system #
####################
/gate/world/daughters/name CTscanner
/gate/world/daughters/insert box
/gate/CTscanner/placement/setTranslation 15. 0. -5 cm
/gate/CTscanner/geometry/setXLength 30. mm
/gate/CTscanner/geometry/setYLength 30. mm
/gate/CTscanner/geometry/setZLength 3. cm
/gate/CTscanner/setMaterial Air
/gate/CTscanner/vis/forceWireframe
/gate/CTscanner/vis/setColor white


#############           ############
# CTSCANNER #   ---->   #  MODULE  #
#############           ############
/gate/CTscanner/daughters/name module
/gate/CTscanner/daughters/insert box
/gate/module/geometry/setXLength 20. mm
/gate/module/geometry/setYLength 20. mm
/gate/module/geometry/setZLength  1. mm
/gate/module/setMaterial Air
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white
/gate/module/vis/setVisible false

############             #############           ###########
#  MODULE  #   ---->     # CLUSTER_0 #   ---->   # PIXEL_0 #
############             #############           ###########
/gate/module/daughters/name pixel
/gate/module/daughters/insert box
/gate/pixel/geometry/setXLength 1 mm
/gate/pixel/geometry/setYLength 0.25 mm
/gate/pixel/geometry/setZLength 0.25 mm
/gate/pixel/setMaterial CdTe
/gate/pixel/vis/setColor magenta

# REPEAT PIXEl_0
/gate/pixel/repeaters/insert cubicArray
/gate/pixel/cubicArray/setRepeatNumberX 80
/gate/pixel/cubicArray/setRepeatNumberY 80
/gate/pixel/cubicArray/setRepeatNumberZ  1
/gate/pixel/cubicArray/setRepeatVector 0.25 0.25 0.0 mm
/gate/pixel/cubicArray/autoCenter true

# ATTACH SYSTEM
/gate/systems/CTscanner/module/attach module
/gate/systems/CTscanner/pixel_0/attach pixel

# ATTACH LAYER
/gate/pixel/attachCrystalSD
